import Head from 'next/head'
import { GetServerSideProps } from 'next'
import { signIn, getSession } from 'next-auth/react'

import styles from '../styles/Login.module.css'
import { FormEvent } from 'react'

export default function Login() {

  const onSubmitToAuth = (event: FormEvent) => {
    event.preventDefault()

    signIn('credentials')
  }

  return (
    <div>
      <Head>
        <title>Next Auth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.auth}>
          <h1>Next Auth</h1>

          <form onSubmit={onSubmitToAuth}>
            <div className={styles.inputWrapper}>
              <label htmlFor="">E-mail</label>
              <input name='email' type="email" placeholder='exemple@mail.com' />
            </div>

            <div className={styles.inputWrapper}>
              <label htmlFor="">Senha</label>
              <input name='password' type="password" placeholder='******' />
            </div>

            <div className={styles.flex}>
              <div className={styles.inputWrapper}>
                <button type='submit' className={styles.success}>Login</button>
              </div>

              <div className={styles.inputWrapper}>
                <button
                  type='submit'
                  className={styles.github}
                >
                  GitHub
                </button>
              </div>
            </div>
          </form>

        </div>
      </main>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const session = await getSession(context)
  let { req } = context
  
  if (session) {
    return {
      redirect: {
        destination: '/home',
        permanent: false
      }
    }
  }

  return {
    props: {
      session
    }
  }
}